# Generated by Django 3.2.4 on 2021-06-06 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('publish_date', models.DateTimeField()),
                ('summary', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
