# Generated by Django 3.2.4 on 2021-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210608_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
